export const 
    ERROR = 'ERROR',
    LOADING = 'LOADING',
    SET_SEARCH_TEXT = 'SET_SEARCH_TEXT',
    FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS',
    FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS',
    SET_LOCATION_LANGUAGE = 'SET_LOCATION_LANGUAGE';